import Head from "next/head";
import { useEffect, useState } from "react";
import {
  FormControl,
  FormLabel,
  FormHelperText,
  Input,
  Button,
  RadioGroup,
  Heading,
  Radio,
  Text,
  Flex,
  Card,
  CardBody,
  HStack,
} from "@chakra-ui/react";
import { FaTwitter, FaLinkedin, FaGithub } from "react-icons/fa";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [interests, setInterests] = useState("");
  const [type, setType] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);

  const inputInterest = (e) => {
    setInterests(e.target.value);
  };

  const inputType = (e) => {
    setType(e.target.value);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    const response = await fetch("../pages/suggest.js", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        interests,
        type,
      }),
    });

    const data = await response.json();
    setResult(data.data);
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>GiftHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Flex direction="column" align="center" justify="center">
          <div w={100}>
            <Text
              className={styles.title}
              fontSize={{ base: "40px", md: "50px", lg: "56px" }}
            >
              GiftHub 🎁
            </Text>
            <Text
              className={styles.description}
              fontSize={{ base: "20px", md: "24px", lg: "28px" }}
            >
              Gifting guide for n00bs
            </Text>
          </div>
        </Flex>
        <div>
          <FormControl m={4}>
            <FormLabel>what are your interests?</FormLabel>
            <input
              onChange={inputInterest}
              placeholder="Batman, Harry Potter, freakish, whatever you like..."
              type="text"
              width="90vw"
              value={interests}
            />
            <FormHelperText>
              Enter your interests and separate them using commas. Leave it blank
              to get random suggestions.
            </FormHelperText>
          </FormControl>
          <FormControl as="fieldset" m={4}>
            <FormLabel as="legend">
              what kind of gift do you want? </FormLabel>
          <RadioGroup name="type" defaultValue="educative">
            <Flex direction="column" spacing="24px">
              <Radio onChange={inputType} value="educative">
                Educative
                </Radio>
                <Radio onChange={inputType} value="scary">
                Scary
                </Radio>
                <Radio onChange={inputType} value="romantic">
                Romantic
                </Radio>
                <Radio onChange={inputType} value="funny">
                Funny
                </Radio>
              </Flex>
            </RadioGroup>
          </FormControl>
                <Flex align="center" justify="center" m={4}>
                  {loading && ( 
                    <Button isLoading colorScheme="gray" size="md">
                    suggest gifts
                    </Button>
                  )}
                  {!loading && (
                    <Button onClick={handleSubmit} colorScheme="gray" size="md">
                      suggest gifts
                    </Button>
                    )}
                  </Flex>
                  </div>
      </main>

      <footer className={styles.footer}>
        <Flex direction="column" align="center" justify="center">
          <div>Liked the Project ? Connect with me and let me know !</div>
          <br />
          <HStack>
            <a
              href="https://twitter.com/_heysahil/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button colorScheme="twitter" leftIcon={<FaTwitter />} size="sm">
                Twitter
              </Button>
            </a>
            <a
              href="https://github.com/sahildotexe"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button
                style={{ background: "black", color: "white" }}
                leftIcon={<FaGithub />}
                size="sm"
              >
                GitHub
              </Button>
            </a>

            <a
              href="https://www.linkedin.com/in/sahilkaling/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button
                style={{ background: "#0A66C2", color: "white" }}
                leftIcon={<FaLinkedin />}
                size="sm"
              >
                LinkedIn
              </Button>
            </a>
          </HStack>
        </Flex>
      </footer>
    </div>
  );
}
